name: setup-pnpm
description: Setup Node and pnpm via Corepack
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: pnpm
    - shell: bash
      run: |
        set -euo pipefail
        corepack enable
        corepack prepare pnpm@9.12.1 --activate
    - shell: bash
      run: pnpm -v
