name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-pnpm
      - run: pnpm i --frozen-lockfile

      - name: Build data
        run: pnpm build:data
        env:
          BDL_PROXY_BASE: https://bdlproxy.hicksrch.workers.dev/bdl
          ALLOW_INJURY_FAILURE: "true"

      - name: Verify BDL
        run: pnpm verify:bdl
        env:
          BDL_PROXY_BASE: https://bdlproxy.hicksrch.workers.dev/bdl
          VERIFY_ALLOW_5XX: "true"

      - name: Tests
        run: pnpm test
