name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      # IMPORTANT: don't pass a conflicting version; let it read packageManager from package.json
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install Node deps
        run: pnpm i --frozen-lockfile

      # Build the data via your Cloudflare proxy; allow injuries to soft-fail
      - name: Build data
        run: pnpm build:data
        env:
          BDL_PROXY_BASE: https://bdlproxy.hicksrch.workers.dev/bdl
          ALLOW_INJURY_FAILURE: "true"

      # Lightweight upstream health check; tolerant of a transient 5xx
      - name: Verify BDL
        run: pnpm verify:bdl
        env:
          BDL_PROXY_BASE: https://bdlproxy.hicksrch.workers.dev/bdl
          VERIFY_ALLOW_5XX: "true"

      # Optional: your unit tests (vitest)
      - name: Tests
        run: pnpm test

