name: Deploy GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.1

      - name: Install deps
        run: pnpm i --frozen-lockfile

      - name: Build data
        run: pnpm build:data
        env:
          BALLDONTLIE_API_KEY: ${{ secrets.BALLDONTLIE_API_KEY }}

      - name: Inject BDL key
        run: pnpm inject:bdl
        env:
          VITE_BDL_KEY: ${{ secrets.BALLDONTLIE_API_KEY }}

      - name: Verify injected key exists in artifact
        run: |
          test -f public/assets/bdl-credentials.js
          node -e "
            const fs=require('fs');
            const s=fs.readFileSync('public/assets/bdl-credentials.js','utf8');
            if(!/const EMBEDDED_KEY = \"(?!__VITE_BDL_KEY__)\"/.test(s)){
              console.error('BDL key placeholder still present');
              process.exit(1);
            }
          "

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Restore placeholder in working tree
        run: pnpm restore:bdl

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
