name: Deploy

on:
  push:
    branches: [main]
  schedule:
    - cron: "23 */6 * * *"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm (and fix PATH)
        shell: bash
        run: |
          npm i -g pnpm@9.12.1
          prefix="$(npm config get prefix)"
          echo "$prefix/bin" >> "$GITHUB_PATH"
          pnpm -v
          which pnpm

      - name: Use dedicated pnpm store
        run: pnpm config set store-dir ~/.pnpm-store

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: pnpm-${{ runner.os }}-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Fetch rosters
        env:
          BALLDONTLIE_API_KEY: ${{ secrets.BALLDONTLIE_API_KEY }}
          DATA_TTL_HOURS: 6
        run: pnpm run fetch:rosters

      - name: Build
        run: pnpm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
