name: Previews pipeline

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "27 7 * * *"   # runs at 07:27 UTC daily
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: previews
  cancel-in-progress: true

jobs:
  build-previews:
    runs-on: ubuntu-latest
    environment: previews
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false   # pnpm version comes from package.json: packageManager

      - name: Install deps
        run: pnpm i --frozen-lockfile

      - name: Stamp date
        id: metadata
        run: echo "date=$(date -u +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"

      - name: Verify Ball Don't Lie API access
        env:
          BDL_PROXY_BASE: https://bdlproxy.hicksrch.workers.dev/bdl
          VERIFY_ALLOW_5XX: "true"   # soft-pass a single upstream 5xx after one retry
        run: pnpm verify:bdl

      # 'pnpm previews' already calls build:data + gen:previews + validate:previews
      - name: Build previews
        env:
          USE_NBA_STATS: "0"
          USE_BREF: "0"
          BDL_PROXY_BASE: https://bdlproxy.hicksrch.workers.dev/bdl
          ALLOW_INJURY_FAILURE: "true"   # don't fail pipeline if /player_injuries keeps 500'ing
        run: pnpm previews

      # Optional: remove this if your 'previews' script already validates
      # - name: Validate previews
      #   run: pnpm validate:previews

      - name: Detect changes
        id: changes
        run: |
          git add -A
          if git diff --cached --quiet --no-ext-diff; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Git identity for PR commits
        if: steps.changes.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Open pull request
        if: steps.changes.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(previews): refresh canonical data and regenerate previews for ${{ steps.metadata.outputs.date }}"
          title: "Auto refresh previews ${{ steps.metadata.outputs.date }}"
          body: "Auto-generated previews. CI fails if stale names are detected."
          branch: "chore/auto-previews-${{ github.run_id }}"
          base: "main"
          delete-branch: true

