name: Previews pipeline

on:
  push:
    branches: [main]
  schedule:
    - cron: "27 7 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: previews
  cancel-in-progress: true

jobs:
  build-previews:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm (and fix PATH)
        shell: bash
        run: |
          npm i -g pnpm@9.12.1
          prefix="$(npm config get prefix)"
          echo "$prefix/bin" >> "$GITHUB_PATH"
          pnpm -v
          which pnpm

      - name: Use dedicated pnpm store
        run: pnpm config set store-dir ~/.pnpm-store

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: pnpm-${{ runner.os }}-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Stamp date
        id: metadata
        run: echo "date=$(date -u +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"

      - name: Generate previews
        env:
          USE_NBA_STATS: "0"
          USE_BREF: "0"
        run: pnpm previews

      - name: Validate previews
        run: pnpm run validate:previews

      - name: Detect changes
        id: changes
        run: |
          if git diff --quiet; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Open pull request
        if: steps.changes.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(previews): refresh canonical data and regenerate previews for ${{ steps.metadata.outputs.date }}"
          title: "Auto refresh previews ${{ steps.metadata.outputs.date }}"
          body: "Auto-generated previews. CI fails if stale names are detected."
          branch: "chore/auto-previews-${{ github.run_id }}"
          base: "main"
          delete-branch: true
